apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: istio-workshop
build:
  artifacts:
  - image: client
    context: client
    docker:
      dockerfile: Dockerfile
  - image: server-v1
    context: server-v1
    docker:
      dockerfile: Dockerfile
  - image: server-v2
    context: server-v2
    docker:
      dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - client/kubernetes/deployment.yaml
    - client/kubernetes/service.yaml
    - client/kubernetes/virtualservice.yaml
    - client/kubernetes/request-authentication.yaml
    - client/kubernetes/authorization-policy.yaml
    - server-v1/kubernetes/deployment.yaml
    - server-v2/kubernetes/deployment.yaml
    - istio/gateway.yaml
    - istio/destinationrule.yaml
    - istio/virtualservice.yaml
    - istio/service.yaml
    - istio/mtls.yaml
