apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-v2
  labels:
    app: server
spec:
  replicas: 1
  template:
    metadata:
      name: server-v2
      labels:
        app: server
        version: v2
    spec:
      containers:
        - name: server-v2
          image: server-v2:1.0.0
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: server
      version: v2
