apiVersion: v1
kind: Service
metadata:
  name: server-v2
  labels:
    version: v2
spec:
  selector:
    app: server-v2
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
