apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-v1
  labels:
    app: server-v1
spec:
  replicas: 1
  template:
    metadata:
      name: server-v1
      labels:
        app: server-v1
    spec:
      containers:
        - name: server-v1
          image: server-v1:1.0.0
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: server-v1
