apiVersion: v1
kind: Service
metadata:
  name: server-v1
  labels:
    version: v1
spec:
  selector:
    app: server-v1
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
